name: learn_flutter_adis
description: "Adis tries to learn Flutter project"
publish_to: "none"
version: 0.0.1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # internal
  bloc: 8.1.4
  flutter_bloc: 8.1.6
  equatable: 2.0.5

  go_router: 14.2.0

  jwt_decoder: 2.0.1

  intl: 0.19.0
  flutter_localizations:
    sdk: flutter

  # persistent
  shared_preferences: 2.2.3
  flutter_secure_storage: 9.2.2

  graphql: 5.1.3
  dio: 5.4.3+1

  # integrations and servicies

  # native
  image_picker: 1.1.2
  share_plus: 9.0.0

  flutter_launcher_icons: 0.13.1
  flutter_native_splash: 2.4.0

  # ui and presentation

  # other

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  generate: true

  assets:
    - assets/icons/
    - assets/fonts/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter/Inter-Thin.ttf
          weight: 100
        - asset: assets/fonts/Inter/Inter-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Inter/Inter-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter/Inter-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Inter/Inter-Black.ttf
          weight: 900

flutter_intl:
  enabled: true
  arb_dir: lib/src/core/localization/l10n
  output_dir: lib/src/core/localization/generated
